# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Joseph Warren
# Generated on: 5/18/2019

@{
    RootModule        = 'WoWAddonManager.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '687c0fac-b389-445a-b940-044301248346'
    Author            = 'Joseph Warren'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Joseph Warren. All rights reserved.'
    Description       = ''
    FunctionsToExport = '*'
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

